CEDS-6196: Standardise back links
hmrc/cds-file-upload-frontend pull request #254
Opened 2024-11-28 11:51 UTC by murthybathini

2024-11-29 09:36 UTC, glidester requested changes
Just one place left where we can remove the referer url

2024-12-02 17:29 UTC, glidester requested changes
Need to reinstate persisting the `mrn` value

2024-12-02 17:29 UTC, glidester commented on app/controllers/MrnEntryController.scala
> -        .map(updateUserAnswersAndRedirect(_, updatedAnswers))
You are no-longer calling `updateUserAnswersAndRedirect` so the `mrn` value is not being saved in the cache any more.

We don't need the `mrnPageRefererUrl` saved anymore but we certainly do still need the `mrn` that is passed in saved to the cache!

2024-12-02 17:29 UTC, glidester commented on test/controllers/MrnEntryControllerSpec.scala
> -      }
This test is still valid and should be reinstated

2024-12-03 10:15 UTC, glidester requested changes

2024-12-03 10:15 UTC, glidester commented on test/controllers/MrnEntryControllerSpec.scala
> +  }
We don't need to reinstate this test as this is regarding the `mrnPageRefererUrl` parameter that no longer exists.

2024-12-03 10:26 UTC, glidester submitted a review, later dismissed

2024-12-05 11:52 UTC, IanWood-HMRC approved these changes

2024-12-05 14:18 UTC, IanWood-HMRC approved these changes

2024-12-05 14:59 UTC, merged